### ISSUE TITLE
开启Gitment后，使用hexo generate报错

### ISSUE THREAD

**Issue by yinshangwei** [ColMugX/hexo-theme-Nlvi#31]
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: bad indentation of a mapping entry at line 76, column 4:
       gitment:

**Comment by colmugx** [comment]
可能是更新迁移的时候出问题了，修复之后会在这里回应

请问这四项有没有对应填好
```
  gitment:
    owner: 
    repo: 
    client_id: 
    client_secret: 
```

**Comment by colmugx** [comment]
https://github.com/ColMugX/hexo-theme-Nlvi/wiki/%E6%B7%BB%E5%8A%A0%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F#gitment

**Comment by yinshangwei** [comment]
四项值填了

**Comment by colmugx** [comment]
@yinshangwei 测试之后发现没有问题
你要确保您的打开是否是准确的
给您一个范本，内容并非真实
```yaml
comments: 
  enable: true
  # disqus: 
  # changyan:
  #   appid: 
  #   appkey: 
  gitment:
    owner: yinshangwei
    repo: https://github.com/yinshangwei/<存放评论项目>
    client_id: 1dxxxx0612xxxxxgce
    client_secret: abcdefghijklmnopqrstuvwxyz
```
实际上如果你其他并不需要用到，可以删掉（可备份，不备份的话，想要找回来的时候，code随时可取）
```yaml
comments: 
  enable: true
  gitment:
    owner: yinshangwei
    repo: https://github.com/yinshangwei/<存放评论项目>
    client_id: 1dxxxx0612xxxxxgce
    client_secret: abcdefghijklmnopqrstuvwxyz
```

**Comment by colmugx** [comment]
另外也可以保持hexo为最新的状态
（不过这个可能需要自己斟酌，因为之前有一个issue是因为更得太快导致的bug...）

**Comment by yinshangwei** [comment]
现在好用了，另外repo地址应该不应该包含前面的`https://github.com/`。
```
comments: 
  enable: true
  gitment:
    owner: linxueyuanstdio
    repo: linxueyuanstdio.github.io
    client_id: 1dxxxx0612xxxxxgce
    client_secret: abcdefghijklmnopqrstuvwxyz
```
