### ISSUE TITLE
代码块自动居中

### ISSUE THREAD

**Issue by counter2015** [ColMugX/hexo-theme-Nlvi#49]
更新后成这样了（大吐血
![](http://ww1.sinaimg.cn/large/005OIjE6ly1fyzfg79zxvj31hc0nfjv1.jpg)
主题配置使用的是clone下来的原版。
hexo配置如下
```
title: not determined yet
subtitle:
description: a personal blog
keywords:
author: counter2015
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://counter2015.github.io
root: /
# permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
#plugins:
        #- hexo-toc
    #  - hexo-server
    #- hexo-spoiler
## Themes: https://hexo.io/themes/

theme: hexo-theme-Nlvi

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:counter2015/counter2015.github.io.git
  branch: master





# Created Time
since: 2018-11-20


visit_counter: true

mathjax: true

```
插件`package.json`配置如下
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.7.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-pug": "0.0.5",
    "hexo-renderer-sass": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-spoiler": "^1.4.4",
    "hexo-toc": "^1.1.0"
  }
}

```
其他主题的代码块能正常显示，如果只有我一个人有这个问题的话那估计就是插件冲突的问题或者别的什么了。

----
UPD1: 
尝试`git checkout`回退到上一个版本，`hexo g`生成时`warn : no layout`，网页无法正常加载
多次切换主题后导致所有主题加载错误，`hexo clean`后恢复正常，但是依然无法修复代码块自动居中。
