### ISSUE TITLE
打赏二维码图片变形

### ISSUE THREAD

**Issue by Roger-WIN** [ColMugX/hexo-theme-Nlvi#68]
![image](https://user-images.githubusercontent.com/25821208/58376989-a242d400-7fa9-11e9-8623-13edb3c2249f.png)
我的打赏二维码图片是长方形的，但在现有的指定宽度和高度的情况下会变形成正方形，这样变扁之后有些不美观。

![image](https://user-images.githubusercontent.com/25821208/58376999-e7ff9c80-7fa9-11e9-9975-f25f1c09a5e5.png)
我尝试着不指定高度，发现这样图片就不会变形了。

当然也可以使用其它等比例缩放图片的方式，我这只是禁用了一条规则，可能算是偷懒性质的最简单方式吧。🤣

**Comment by Roger-WIN** [comment]
当然也可以使用其它等比例缩放图片的方式，我这只是禁用了一条规则，可能算是偷懒性质的最简单方式吧。🤣

**Comment by colmugx** [comment]
尝试了几个方法，最后确定还是不换行用比例尺寸。如果移动端图片稍小的话，我加入了适配`lightbox`，如果设置有启用`lightbox`的话，有「放大查看」的效果

**Comment by Roger-WIN** [comment]
![image](https://user-images.githubusercontent.com/25821208/58380500-7b55c380-7fe4-11e9-93c3-31ac26f14da0.png)
图片左下角的文字是不是有点多余啊？如果要有的话，我觉得可以直接显示「支付宝」、「PayPal」的字样（不过这样就牵涉到多语言的问题了），或者允许自定义。

**Comment by colmugx** [comment]
已更新`message`设定，不设置时不显示
```yaml
reward:
  enable: true
  message:
  qrcode:
    alipay:
      url:
      message:
    wechat:
      url:
      message:
    paypal:
      url:
      message:
```
